on:
  push:
    branches:
      - master
      - development
      - chore/*
      - feat/*
      - release/*
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Terraform Setup' 
      uses: hashicorp/setup-terraform@v2

    - name: 'Terraform Init'
      run: terraform init

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true